language: node_js
node_js:
  - node
cache:
  directories:
    #Cache Client npm install files
    - ${TRAVIS_BUILD_DIR}/client/.npm
    - ${TRAVIS_BUILD_DIR}/client/node-modules

    #Cache Server npm install files
    - ${TRAVIS_BUILD_DIR}/server/text/.npm
    - ${TRAVIS_BUILD_DIR}/server/text/node-modules
    - ${TRAVIS_BUILD_DIR}/server/call/.npm
    - ${TRAVIS_BUILD_DIR}/server/call/node-modules

install: ${TRAVIS_BUILD_DIR}/install-dependencies.sh
script:
  #Run jest unit tests on client
  - cd ${TRAVIS_BUILD_DIR}/client
  - jest
  #Run cypress tests on client
#  - npm run cypress:run
  # Run tests for the text version of our API
  - cd ${TRAVIS_BUILD_DIR}/server/text
  - jest
  # Run tests for the call version of our API
  - cd ${TRAVIS_BUILD_DIR}/server/call
  - jest
before_deploy:
  - cd ${TRAVIS_BUILD_DIR}/server/local_dependencies/aws-api-gateway-return
  - npm install --production
  - cd ${TRAVIS_BUILD_DIR}/server/local_dependencies/simple-bandwidth-api
  - npm install --production
  # create text zip
  - cd ${TRAVIS_BUILD_DIR}/server/text
  - rm -r node_modules
  - npm install --production # for lambda zip to not be bloated with dev dependencies
  - zip context_call_v2_text -r node_modules/ index.js
  # create call zip
  - cd ${TRAVIS_BUILD_DIR}/server/call
  - rm -r node_modules
  - npm install --production # for lambda zip to not be bloated with dev dependencies
#Deploy to lambda via dpl
deploy:
  # provider: script
  # script: ${TRAVIS_BUILD_DIR}/deploy.sh
  # on:
  #   branch: modular_lambda
  provider: lambda
  function_name: "ContextCallV2"
  region: "us-west-2"
  role: "arn:aws:iam::957512267502:role/LambdaDeployment"
  runtime: "nodejs6.10"
  handler_name: "handler"
  zip: "${TRAVIS_BUILD_DIR}/server/text/context_call_v2_text.zip"
  access_key_id: $AWSACCESSKEY
  secret_access_key: $SECRETACCESSKEY
  environment_variables:
    - SECRET=$AWS_LAMBDA_ENV_SECRET
    - API_SECRET=$AWS_LAMBDA_ENV_API_SECRET
    - API_TOKEN=$AWS_LAMBDA_ENV_API_TOKEN
    - PHONE_NUMBER=$AWS_LAMBDA_ENV_PHONE_NUMBER
    - USER_ID=$AWS_LAMBDA_ENV_USER_ID
    - CALLBACK_URL=$AWS_LAMBDA_ENV_CALLBACK_URL
  on:
    branch: modular_lambda
after_deploy:
  rm ${TRAVIS_BUILD_DIR}/context_call_v2_text.zip