language: node_js
node_js:
  - node
cache:
  directories:
    #Cache Client npm install files
    - ~/build/BandwidthExamples/context-call/client/.npm
    - ~/build/BandwidthExamples/context-call/client/node-modules

    #Cache Server npm install files
    - ~/build/BandwidthExamples/context-call/server/.npm
    - ~/build/BandwidthExamples/context-call/server/node-modules

install: ./install-dependencies.sh
script:
  #Run jest unit tests on client
  - cd ~/build/BandwidthExamples/context-call/client
  - jest
  #Run cypress tests on client
#  - npm run cypress:run
  # Run tests for the text version of our API
  - cd ~/build/BandwidthExamples/context-call/server/text
  - jest
  # Run tests for the call version of our API
  - cd ~/build/BandwidthExamples/context-call/server/call
  - jest
#Deploy to lambda
deploy:
  provider: lambda
  function_name: "ContextCallV2"
  region: "us-west-2"
  role: "arn:aws:iam::957512267502:role/lambda_basic_execution"
  runtime: "nodejs4.3"
  handler_name: "handler"
  access_key_id: "AWS ACCESS KEY ID"
  secret_access_key: "AWS SECRET ACCESS KEY"
