language: node_js
before_install: npm cache clean
install: ./install-dependencies.sh
script:
  #Run jest unit tests on client
  - cd ~/build/BandwidthExamples/context-call/client
  - jest
  #Run cypress tests on client
#  - npm run cypress:run
  #Run jest unit tests on server
  - cd ~/build/BandwidthExamples/context-call/server
  - jest
