language: node_js
node_js:
  - node
cache:
  directories:
    #Cache Client npm install files
    - ${TRAVIS_BUILD_DIR}/client/.npm
    - ${TRAVIS_BUILD_DIR}/client/node-modules

    #Cache Server npm install files
    - ${TRAVIS_BUILD_DIR}/server/text/.npm
    - ${TRAVIS_BUILD_DIR}/server/text/node-modules
    - ${TRAVIS_BUILD_DIR}/server/call/.npm
    - ${TRAVIS_BUILD_DIR}/server/call/node-modules
    - ${TRAVIS_BUILD_DIR}/server/orders-get/.npm
    - ${TRAVIS_BUILD_DIR}/server/orders-get/node-modules

install: ${TRAVIS_BUILD_DIR}/install-dependencies.sh
script:
  #Run jest unit tests on client
  - cd ${TRAVIS_BUILD_DIR}/client
  - jest
  #Run cypress tests on client
#  - npm run cypress:run
  # Run tests for the text version of our API
  - cd ${TRAVIS_BUILD_DIR}/server/text/
  - jest
  # Run tests for the call version of our API
  - cd ${TRAVIS_BUILD_DIR}/server/call/
  - jest
  # Run http callback tests
  - cd ${TRAVIS_BUILD_DIR}/server/wait/
  - jest
  # Run tests for getting orders from the database
  - cd ${TRAVIS_BUILD_DIR}/server/orders-get/
  - jest
before_deploy:
  - cd ${TRAVIS_BUILD_DIR}/server/local_dependencies/aws-api-gateway-return
  - npm install --production
  - cd ${TRAVIS_BUILD_DIR}/server/local_dependencies/simple-bandwidth-api
  - npm install --production
  # create text zip
  - cd ${TRAVIS_BUILD_DIR}/server/text
  - rm -r node_modules
  - npm install --production # for lambda zip to not be bloated with dev dependencies
  - zip context_call_v2_text -r node_modules/ index.js
  # create call zip
  - cd ${TRAVIS_BUILD_DIR}/server/call
  - rm -r node_modules
  - npm install --production # for lambda zip to not be bloated with dev dependencies
  - zip context_call_v2_call -r node_modules/ index.js
  # create wait zip
  - cd ${TRAVIS_BUILD_DIR}/server/wait
  - zip context_call_v2_wait index.js
  # create orders-get zip
  - cd ${TRAVIS_BUILD_DIR}/server/orders-get
  - zip context_call_v2_orders_get index.js
#Deploy to lambda via dpl
deploy:
  - provider: lambda
    function_name: "ContextCallV2Text"
    region: "us-west-2"
    role: "arn:aws:iam::957512267502:role/LambdaDeployment"
    runtime: "nodejs6.10"
    handler_name: "handler"
    zip: "${TRAVIS_BUILD_DIR}/server/text/context_call_v2_text.zip"
    access_key_id: $AWSACCESSKEY
    secret_access_key: $SECRETACCESSKEY
    environment_variables:
      - SECRET=$AWS_LAMBDA_ENV_SECRET
      - API_SECRET=$AWS_LAMBDA_ENV_API_SECRET
      - API_TOKEN=$AWS_LAMBDA_ENV_API_TOKEN
      - PHONE_NUMBER=$AWS_LAMBDA_ENV_PHONE_NUMBER
      - USER_ID=$AWS_LAMBDA_ENV_USER_ID
      - CALLBACK_WAIT_URL=$AWS_LAMBDA_ENV_CALLBACK_WAIT_URL
    on:
      branch: database-lambda
  - provider: lambda
    function_name: "ContextCallV2Call"
    region: "us-west-2"
    role: "arn:aws:iam::957512267502:role/LambdaDeployment"
    runtime: "nodejs6.10"
    handler_name: "handler"
    zip: "${TRAVIS_BUILD_DIR}/server/call/context_call_v2_call.zip"
    access_key_id: $AWSACCESSKEY
    secret_access_key: $SECRETACCESSKEY
    environment_variables:
      - SECRET=$AWS_LAMBDA_ENV_SECRET
      - API_SECRET=$AWS_LAMBDA_ENV_API_SECRET
      - API_TOKEN=$AWS_LAMBDA_ENV_API_TOKEN
      - PHONE_NUMBER=$AWS_LAMBDA_ENV_PHONE_NUMBER
      - USER_ID=$AWS_LAMBDA_ENV_USER_ID
      - CALLBACK_WAIT_URL=$AWS_LAMBDA_ENV_CALLBACK_WAIT_URL
    on:
      branch: database-lambda
  - provider: lambda
    function_name: "ContextCallV2Wait"
    region: "us-west-2"
    role: "arn:aws:iam::957512267502:role/LambdaDeployment"
    runtime: "nodejs6.10"
    handler_name: "handler"
    zip: "${TRAVIS_BUILD_DIR}/server/wait/context_call_v2_wait.zip"
    access_key_id: $AWSACCESSKEY
    secret_access_key: $SECRETACCESSKEY
    on:
      branch: database-lambda
  - provider: lambda
      function_name: "ContextCallV2OrdersGet"
      region: "us-west-2"
      role: "arn:aws:iam::957512267502:role/LambdaDeployment"
      runtime: "nodejs6.10"
      handler_name: "handler"
      zip: "${TRAVIS_BUILD_DIR}/server/wait/context_call_v2_orders_get.zip"
      access_key_id: $AWSACCESSKEY
      secret_access_key: $SECRETACCESSKEY
      on:
        branch: database-lambda
after_deploy:
  - rm ${TRAVIS_BUILD_DIR}/server/text/context_call_v2_text.zip
  - rm ${TRAVIS_BUILD_DIR}/server/call/context_call_v2_call.zip
  - rm ${TRAVIS_BUILD_DIR}/server/wait/context_call_v2_wait.zip
  - rm ${TRAVIS_BUILD_DIR}/server/wait/context_call_v2_orders_get.zip
