language: node_js
node_js:
  - node
cache:
  directories:
    #Cache Client npm install files
    - ${TRAVIS_BUILD_DIR}/client/.npm
    - ${TRAVIS_BUILD_DIR}/client/node-modules

    #Cache Server npm install files
    - ${TRAVIS_BUILD_DIR}/server/text/.npm
    - ${TRAVIS_BUILD_DIR}/server/text/node-modules
    - ${TRAVIS_BUILD_DIR}/server/call/.npm
    - ${TRAVIS_BUILD_DIR}/server/call/node-modules

install: ${TRAVIS_BUILD_DIR}/install-dependencies.sh
script:
  #Run jest unit tests on client
  - cd ${TRAVIS_BUILD_DIR}/client
  - jest
  #Run cypress tests on client
#  - npm run cypress:run
  # Run tests for the text version of our API
  - cd ${TRAVIS_BUILD_DIR}/server/text
  - jest
  - rm -r node_modules; npm install --production # for lambda zip to not be bloated with dev dependencies
  # Run tests for the call version of our API
  - cd ${TRAVIS_BUILD_DIR}/server/call
  - jest
  - rm -r node_modules; npm install --production # for lambda zip to not be bloated with dev dependencies
#Deploy to lambda via script
deploy:
  # provider: script
  # script: ${TRAVIS_BUILD_DIR}/deploy.sh
  # on:
  #   branch: modular_lambda
  provider: lambda
  skip_cleanup: false
  function_name: "ContextCallV2"
  region: "us-west-2"
  role: "arn:aws:iam::957512267502:role/LambdaDeployment"
  runtime: "nodejs6.10"
  handler_name: "handler"
  zip: "${TRAVIS_BUILD_DIR}/server/text"
  access_key_id: $AWSACCESSKEY
  secret_access_key: $SECRETACCESSKEY
  environment_variables:
    - SECRET=password
    - BUILD_DIR=$TRAVIS_BUILD_DIR
  on:
    branch: modular_lambda
